GRANT USAGE ON *.* TO 'cs461'@'%';
GRANT ALL PRIVILEGES ON `CS461`.* TO 'cs461'@'%';
GRANT ALL PRIVILEGES ON *.* TO 'root'@'localhost' WITH GRANT OPTION;
GRANT PROXY ON ''@'' TO 'root'@'localhost' WITH GRANT OPTION;
